### ISSUE TITLE
modbus_write has a problem when func == WRITE_COILS

### ISSUE THREAD

**Issue by hlvas** [fanzhe98/modbuspp#5]
When multiple coils are written the modbus_write writes wrongfully the low byte of the requested coil
Requested Number of Coil Low Byte should be:
` to_send[11] = (uint8_t) (amount);`
 instead of : 
`to_send[11] = (uint8_t) (amount>>8);`

**Comment by BlackHoneyBear** [comment]
i do this butt nothings is write on coils

**Comment by simotronic** [comment]
Hi, I haven't tried the write coils yet. I was interested in reading back data that is formatted as single precision float as per IEEE. That requires reading 32 bit registers. That said, as I'm sure you've discovered that endianess (Big or Little Endian), is an issue. So you have to swap bytes around to correctly format the data. This is particularly true with different platforms such as PLCs. Take a look at the snap7 project. The author Davide has provided functions to address this. In fact he includes compiler directives to take care of it! Libnodave is a little more difficult.
I'm planning on using the Modbus software to address a block of registers that are part of a structure so that mapping the data can be easily processed.
Good luck byte swapping!!
Simon

**Comment by konsolenritter** [comment]
Please proof if my last commit to https://github.com/konsolenritter/modbuspp/commit/3318c0b66b9b827f73482217b2444fb82dea6e42 does work for you. (A lot of fixing even regarding the WRITE_COILS.)

**Comment by fz-lyu** [comment]
@konsolenritter your fix seems to be correct. Thanks!
